# DB properties are to be provided via environment variables by Docker Compose
#db:
#  url: jdbc:postgresql://localhost:5432/phaedra
#  username: phaedra
#  password: phaedra

logging:
  file:
    plateservice.log
    
spring:
  jackson:
    serialization:
      indent_output: true

server:
  servlet:
    context-path: /phaedra/plate-service