# DB properties are to be provided via environment variables by Docker Compose
#db:
#  url: jdbc:postgresql://localhost:5432/plateservice
#  username: plateservice
#  password: plateservice

logging:
  file:
    /var/log/plateservice.log
    
spring:
  jackson:
    serialization:
      indent_output: true

#server:
#  servlet:
#    context-path: /phaedra/plate-service