version: '3'

services:
  db:
    image: postgres:13
    hostname: plateservice-db
    container_name: plateservice-db
    networks:
      - phaedra2
    environment:
      - POSTGRES_DB=plateservice
      - POSTGRES_USER=plateservice
      - POSTGRES_PASSWORD=plateservice
    volumes:
      - ./sql/populate_database.sh:/docker-entrypoint-initdb.d/populate_database.sh:ro
      - ./sql/1-create-tables.sql:/opt/1-create-tables.sql:ro
  app:
    image: openanalytics/phaedra2-plateservice
    hostname: plateservice-app
    container_name: plateservice-app
    networks:
      - phaedra2
    ports:
      - 8080:8080
    depends_on:
      - db
    environment:
      - DB_URL=jdbc:postgresql://plateservice-db:5432/plateservice
      - DB_USERNAME=plateservice
      - DB_PASSWORD=plateservice

networks:
  phaedra2: