version: '3.5'

services:
  plates_db:
    image: postgres:13-alpine
    restart: always
    hostname: plates-db
    container_name: plates-db
    networks:
      - private
    environment:
      - POSTGRES_DB=phaedra2
      - POSTGRES_USER=phaedra_usr
      - POSTGRES_PASSWORD=phaedra_usr
    volumes:
      - ./db/0-create-schema.sql:/opt/0-create-schema.sql
      - ./db/1-create-tables.sql:/opt/1-create-tables.sql
      - ./sh:/docker-entrypoint-initdb.d/
    ports:
      - 8765:5432
  plate_service:
    image: phaedra2-plateservice:0.0.1-SNAPSHOT
    hostname: phaedra2-plateservice
    container_name: phaedra2-plateservice
    networks:
      - private
      - phaedra2
    depends_on:
      - plates_db
    environment:
      - DB_URL=jdbc:postgresql://plates-db:5432/phaedra2?currentSchema=plates
      - DB_USER=phaedra_usr
      - DB_PASSWORD=phaedra_usr
    ports:
      - 3003:3003

networks:
  private:
    name: private
    external: false
  phaedra2:
    external:
      name: phaedra2