server:
  servlet:
    context-path: /phaedra/plate-service
  port: 3003

spring:
  application:
    name: PHAEDRA-PLATE-SERVICE
#  datasource:
#    driver-class-name: org.postgresql.Driver
#    url: jdbc:postgresql://localhost:5432/phaedra2?currentSchema=plates
#    username: phaedra_usr
#    password: phaedra_usr
  jackson:
    serialization:
      indent_output: true

logging:
  file:
    name: /var/log/plateservice.log

eureka:
  instance:
    appname: ${spring.application.name}
  client:
    service-url:
      defaultZone: ${SERVICE_REGISTRY:http://localhost:8761/eureka}