server:
  servlet:
    context-path: /phaedra/plate-service
  port: 3003

spring:
  application:
    name: phaedra-plate-service
  jackson:
    serialization:
      indent_output: true
  cloud:
    kubernetes:
      enabled: false

logging:
  file:
    name: /var/log/plateservice.log

eureka:
  client:
    enabled: true

