keycloak-base-url: http://keycloak:8080

server:
  servlet:
    context-path: /phaedra/plate-service
  port: 8080

spring:
  application:
    name: phaedra-plate-service
  jackson:
    serialization:
      indent_output: true
  cloud:
    kubernetes:
      enabled: true
  liquibase:
    enabled: false
  security:
    oauth2:
      client:
        registration:
          keycloak:
            provider: keycloak
#            client-id: phaedra2-pipeline-service
#            client-secret: ???
            authorization-grant-type: client_credentials
        provider:
          keycloak:
            authorization-uri: ${keycloak-base-url}/auth/realms/phaedra2/protocol/openid-connect/auth
            token-uri: ${keycloak-base-url}/auth/realms/phaedra2/protocol/openid-connect/token
            user-info-uri: ${keycloak-base-url}/auth/realms/phaedra2/protocol/openid-connect/userinfo
            jwk-set-uri: ${keycloak-base-url}/auth/realms/phaedra2/protocol/openid-connect/certs
      resourceserver:
        jwt:
          jwk-set-uri: http://localhost
  graphql:
    graphiql:
      enabled: true
      path: /graphiql


logging:
  file:
    name: /var/log/plateservice.log

