# automatically gets loaded by Spring Cloud Kubernetes when using Kubernetes
server:
  port:
    8080

spring:
  cloud:
    kubernetes:
      enabled: true
  graphql:
    graphiql:
      enabled: true
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: https://keycloak.phaedra.poc.openanalytics.io/auth/realms/phaedra2/protocol/openid-connect/certs
  kafka:
    bootstrap-servers: kafka-service:9092
    producer:
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    consumer:
      value-deserializer: org.apache.kafka.common.serialization.BytesDeserializer

