# automatically gets loaded by Spring Cloud Kubernetes when using Kubernetes
server:
  port:
    8080

spring:
  cloud:
    kubernetes:
      enabled: true
  graphql:
    graphiql:
      enabled: true
  kafka:
    bootstrap-servers: kafka-service:9092
    producer:
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    consumer:
      value-deserializer: org.apache.kafka.common.serialization.BytesDeserializer

